<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{
    // example usage: findBy('[rR]owling')
    public function findByStr($str)
    {
        $criteria = array('title' => '*' . trim($str) . '*');
        $result = $this->findBy($criteria);

        return $result;
    }
}
