<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Book;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Adapter\ArrayAdapter;

/**
 * BooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{
    /** Looks for books with ISBN/title/author/genre mathching given regex pattern.
     *
     * @param string $pattern
     * 
     * @param int $page
     * 
     * @return Pagerfanta\Pagerfanta
    */
    public function query($pattern, $page = 1)
    {
        $pattern = '/'.strtoupper(trim($pattern)).'/';
        $result = array();
        // If regex valid
        if (@preg_match($pattern, null) !== false) {
            $books = $this->findAll();
            foreach ($books as $book) {
                if (preg_match($pattern, strtoupper($book->getISBN()))
                || preg_match($pattern, strtoupper($book->getTitle()))
                || preg_match($pattern, strtoupper($book->getAuthor()))
                || preg_match($pattern, strtoupper($book->getGenre()))
                ) {
                    array_push($result, $book);
                }
            }
        }
        $paginator = new Pagerfanta(new ArrayAdapter($result));
        $paginator->setMaxPerPage(Book::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
}
